Repository MessageCloud/gateway-php, pull requests merged in 2019-10, with the labels that each got.

#17 Added missing extensions requirement in composer.json
  composer.json
  composer.lock
Labels: enhancement

#18 package renamed to messagecloud/gateway
  composer.json
  composer.lock
Labels: enhancement

#19 Replace usage of txtNation with MessageCloud
  README.md
  classes/Exceptions/SMSMessageException.php
  classes/Request.php
  classes/Result.php
  classes/SMSMessage.php
  classes/SMSMessageResult.php
  composer.json
  composer.lock
  examples/send_free_message.php
  tests/SMSMessageTest.php
Labels: enhancement

#23 Change package name to messagecloud/gateway-php
  README.md
  composer.json
  composer.lock
Labels: bug

#27 Add PHPCS and bump minimum PHP version to 7.2
  .gitignore
  classes/Exceptions/SMSMessageException.php
  classes/Request.php
  classes/Result.php
  classes/SMSMessage.php
  classes/SMSMessageResult.php
  composer.json
  composer.lock
  phpcs.xml
  tests/SMSMessageTest.php
Labels: dependencies, enhancement

#29 Add PHPStan
  classes/Request.php
  classes/Result.php
  classes/SMSMessage.php
  classes/SMSMessageResult.php
  composer.json
  composer.lock
  phpstan.neon
  tests/SMSMessageTest.php
Labels: dependencies, enhancement

#34 Remove dependency on monolog/monolog dependency
  classes/Request.php
  classes/SMSMessage.php
  composer.json
  composer.lock
Labels: enhancement

#38 Add type hinting to success method in Result class
  classes/Result.php
Labels: enhancement

#40 Add return type hints in SMSMessage class
  classes/SMSMessage.php
Labels: enhancement
